name: Python Pipeline
on: push
jobs:
  test:
    name: Test Python Script
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Run Python Script
      run: python hello.py
  create_artifact:
    name: Create Artifact
    runs-on: ubuntu-latest
    needs: test 
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: hello_world_artifact
        path: .       
